apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt
  name: mqtt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
#      initContainers:
#      - name: volume-mount-hack
#        image: busybox
#        imagePullPolicy: IfNotPresent
##        command: ["sh", "-c", "chown -R 1883:1883 /mosquitto"]
#        command: ["sh", "-c", "sleep 1"]
##        volumeMounts:
##        - name: data-volume
##          mountPath: /mosquitto/data/mosquitto.db
      containers:
      - image: eclipse-mosquitto
        name: mqtt
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1883
          - containerPort: 9001
        volumeMounts:
          - name: config-file
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
          - name: config-file
            mountPath: /mosquitto/config/mosquitto.passwd
            subPath: mosquitto.passwd
          - name: data-volume
            mountPath: /mosquitto/data
        
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        fsGroup: 1883
        runAsGroup: 1883
        runAsUser: 1883
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-mqtt
        - name: config-file
          configMap:
            name: cm-mosquitto-conf 
            defaultMode: 0600    # Only the owner (1883) can read/write

